synapse:
  admin_token: syt_your_admin_token
  server: https://matrix.your.server
  domain: your.server # i.e. the part after the : in your matrix ID
hosts:
  - register.matrix.your.server
email:
  host: mail.your.server
  port: 587
  username: registrations@your.server
  password: your_password
  tls: true
admin:
  email: admin@your.server
trust_proxy: false
policy_version: "1.0" # leave unset if users should not automatically accept the Matrix privacy policy
form_secret: "your-form-secret"
auto_join:
  - "!your_room_id:your.server"
legal:
  - title: "Terms of Service"
    url: "https://matrix.your.server/_matrix/consent"
retention:
  - started: 2
  - completed: 30
logo_url: "https://matrix.your.server/logo.png"
