# Generated by Django 5.2.7 on 2026-02-27 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    def backfill_started(apps, schema_editor):
        UserRegistration = apps.get_model("registration", "UserRegistration")
        RegistrationEvent = apps.get_model("registration", "RegistrationEvent")

        to_create = []
        batch = 1000

        for r in UserRegistration.objects.all().only("id", "timestamp"):
            to_create.append(
                RegistrationEvent(
                    registration_id=r.id,
                    type="started",
                    occurred_at=r.timestamp,
                    data={},
                )
            )

        if to_create:
            RegistrationEvent.objects.bulk_create(to_create, batch_size=batch)

    dependencies = [
        ("registration", "0006_alter_userregistration_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistrationEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("username_check_ok", "Username availability confirmed"),
                            (
                                "username_check_fail",
                                "Username unavailable / check failed",
                            ),
                            ("email_submitted", "Email submitted"),
                            ("email_verification_sent", "Verification email sent"),
                            (
                                "email_verification_send_failed",
                                "Verification email failed to send",
                            ),
                            ("email_verified", "Email verified"),
                            ("reason_submitted", "Registration reason submitted"),
                            ("requested", "Registration requested (awaiting admin)"),
                            ("approved", "Approved by admin"),
                            ("denied", "Denied by admin"),
                            ("password_form_opened", "Password set link opened"),
                            ("user_created", "Synapse user created"),
                            ("user_create_failed", "Synapse user creation failed"),
                            ("autojoin_ok", "Auto-join room succeeded"),
                            ("autojoin_fail", "Auto-join room failed"),
                            ("consent_ok", "Consent submitted & verified"),
                            ("consent_fail", "Consent submission/verification failed"),
                            ("completed", "Registration completed"),
                        ],
                        max_length=64,
                    ),
                ),
                ("occurred_at", models.DateTimeField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("data", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="registration.userregistration",
                    ),
                ),
            ],
            options={
                "ordering": ["occurred_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["registration", "occurred_at"],
                        name="registratio_registr_1dd869_idx",
                    ),
                    models.Index(
                        fields=["type", "occurred_at"],
                        name="registratio_type_7cda33_idx",
                    ),
                ],
            },
        ),
        migrations.RunPython(backfill_started, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="registrationevent",
            name="occurred_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.RemoveField(
            model_name="userregistration",
            name="timestamp",
        ),
    ]
