# Generated by Django 5.2.7 on 2026-02-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0007_remove_userregistration_timestamp_registrationevent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registrationevent",
            name="type",
            field=models.CharField(
                choices=[
                    ("started", "Started"),
                    ("username_check_ok", "Username availability confirmed"),
                    ("username_check_fail", "Username unavailable / check failed"),
                    ("email_submitted", "Email submitted"),
                    ("email_verification_sent", "Verification email sent"),
                    (
                        "email_verification_send_failed",
                        "Verification email failed to send",
                    ),
                    ("email_verified", "Email verified"),
                    ("reason_submitted", "Registration reason submitted"),
                    ("requested", "Registration requested (awaiting admin)"),
                    (
                        "admin_notified",
                        "Matrix: admin room notified of registration request",
                    ),
                    (
                        "admin_notification_failed",
                        "Matrix: Failed to notify admin room",
                    ),
                    ("approved", "Approved by admin"),
                    ("denied", "Denied by admin"),
                    ("password_form_opened", "Password set link opened"),
                    ("user_created", "Synapse user created"),
                    ("user_create_failed", "Synapse user creation failed"),
                    ("autojoin_ok", "Auto-join room succeeded"),
                    ("autojoin_fail", "Auto-join room failed"),
                    ("consent_ok", "Consent submitted & verified"),
                    ("consent_fail", "Consent submission/verification failed"),
                    ("welcome_sent", "Matrix welcome message sent"),
                    ("welcome_send_failed", "Matrix welcome message failed to send"),
                    ("completed", "Registration completed"),
                ],
                max_length=64,
            ),
        ),
    ]
